# Generated by Django 5.1.3 on 2024-12-11 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=150, unique=True, verbose_name='Назва'),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name='URL',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Категорію',
                'verbose_name_plural': 'Категорії',
                'db_table': 'category',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                (
                    'role',
                    models.CharField(
                        choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager')],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('quantity', models.IntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[('pending', 'Pending'), ('completed', 'Completed')],
                        max_length=50,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'client',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.client'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    'method',
                    models.CharField(
                        choices=[
                            ('credit_card', 'Credit Card'),
                            ('paypal', 'PayPal'),
                            ('cash', 'Cash'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'transaction_id',
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('completed', 'Completed'),
                            ('failed', 'Failed'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.order'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=150, unique=True, verbose_name='Назва'),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name='URL',
                    ),
                ),
                (
                    'description',
                    models.TextField(blank=True, null=True, verbose_name='Опис'),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='products/',
                        verbose_name='Відображення',
                    ),
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=7, verbose_name='Ціна'  # type: ignore
                    ),
                ),
                (
                    'discount',
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,  # type: ignore
                        max_digits=4,
                        verbose_name='Знижка в %',
                    ),
                ),
                (
                    'quantity',
                    models.PositiveIntegerField(default=0, verbose_name='Кількість'),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.categories',
                        verbose_name='Категорія',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'продукти',
                'db_table': 'product',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='core.products'
            ),
        ),
    ]
